// The named fixtures of criterion 45 (the TUNING corpus), generated by test code from small invented logical datasets. Each
// fixture carries its ground-truth mapping (per column, in file order) and its golden canonical CSV (the canonical headers
// in schema order, dot decimals, ISO dates, canonical statuses and warehouse codes). Nothing is downloaded; every company,
// person and identifier is invented.

import { concat, cp1252, utf16le, utf8, utf8Bom } from '../../ingest-kit/corpus';
import { formatCents, formatDate, STATUS_WORDS, type DateStyle, type NumberStyle } from './gen';

export type Kind = 'inventory' | 'shipments';
export type LogicalRow = Record<string, string>;

const INVENTORY_FIELDS = ['sku', 'product_name', 'category', 'warehouse', 'quantity', 'reorder_point', 'unit_cost', 'avg_daily_usage', 'lead_time_days'];
const SHIPMENT_FIELDS = ['shipment_id', 'origin', 'destination', 'carrier', 'status', 'ship_date', 'estimated_delivery', 'actual_delivery', 'shipping_cost'];
export const CANONICAL_FIELDS: Record<Kind, string[]> = { inventory: INVENTORY_FIELDS, shipments: SHIPMENT_FIELDS };

const PRODUCTS = ['Wireless Barcode Scanner', 'Label Printer', 'Pallet Wrap Film', 'Corrugated Box 12x12x12', 'Safety Gloves', 'Thermal Labels', 'Packing Tape', 'Forklift Battery', 'Shelf Bracket', 'Hand Truck'];
const CATEGORIES = ['Electronics', 'Packaging', 'Safety', 'Hardware', 'Labels', 'Equipment'];
const CARRIERS = ['Northstar Freight', 'BlueLine Logistics', 'Cascade Carriers', 'Summit Express', 'Redwood Transport'];
const CITIES = ['Houston, TX', 'San Antonio, TX', 'Phoenix, AZ', 'Denver, CO', 'Kansas City, MO', 'Nashville, TN', 'Miami, FL', 'Charlotte, NC'];
const WH = ['WH-DFW', 'WH-ATL', 'WH-ORD', 'WH-LAX', 'WH-EWR'];
const STATUSES = ['delivered', 'in_transit', 'pending', 'cancelled'];

const money = (cents: number): string => `${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, '0')}`;
const iso = (day: number): string => `2026-03-${String(day).padStart(2, '0')}`;

export function inventoryRows(n = 12): LogicalRow[] {
  return Array.from({ length: n }, (_, i) => ({
    sku: `ELC-${9001 + i * 2}`,
    product_name: `${PRODUCTS[i % PRODUCTS.length]}`,
    category: CATEGORIES[i % CATEGORIES.length] as string,
    warehouse: WH[i % WH.length] as string,
    quantity: String(20 + ((i * 37) % 900)),
    reorder_point: String(10 + ((i * 13) % 120)),
    unit_cost: money(850 + ((i * 1373 + 251) % 150000)),
    avg_daily_usage: money(150 + ((i * 97) % 2000)),
    lead_time_days: String(2 + ((i * 5) % 40))
  }));
}

export function shipmentRows(n = 12): LogicalRow[] {
  return Array.from({ length: n }, (_, i) => {
    const status = STATUSES[i % 4] as string;
    const day = 1 + ((i * 2) % 20);
    return {
      shipment_id: `SHP-${900001 + i * 3}`,
      origin: WH[i % WH.length] as string,
      destination: CITIES[(i + 1) % CITIES.length] as string,
      carrier: CARRIERS[i % CARRIERS.length] as string,
      status,
      ship_date: iso(day),
      estimated_delivery: iso(day + 3),
      actual_delivery: status === 'delivered' ? iso(day + 2 + (i % 3)) : '',
      shipping_cost: money(40000 + ((i * 7919) % 120000))
    };
  });
}

export type Encoding = 'utf8' | 'utf8bom' | 'utf16le' | 'cp1252';

export interface RenderSpec {
  headers: Record<string, string>;
  /** Field order in the file (default: schema order). Fields absent here are omitted from the file. */
  order?: string[];
  delimiter: string;
  numberStyle: NumberStyle;
  dateStyle: DateStyle;
  statusWords: keyof typeof STATUS_WORDS | string[];
  encoding: Encoding;
  banner?: string[];
  totalRow?: string[];
  extra?: Array<{ header: string; values: (i: number) => string }>;
  warehouseStyle?: 'code' | 'name' | 'plant';
  eol?: '\n' | '\r\n';
}

export interface Fixture {
  name: string;
  kind: Kind;
  bytes: Uint8Array;
  hints: { fileName: string; extension: string };
  /** The user confirmations the file needs to be read (encoding confirmation). */
  options: Record<string, string>;
  /** Per column of the header row, in file order: the canonical field a person would choose, or null. */
  truth: Array<string | null>;
  headers: string[];
  logical: LogicalRow[];
  /** Golden canonical CSV of the logical rows (all canonical columns, schema order). */
  golden: string;
  /** Status words as written in the file, with their canonical meaning. */
  statusMap: Array<[word: string, status: string]>;
  /** Warehouse values as written, for files whose warehouses are not the known codes. */
  warehouseMap?: Array<[value: string, code: string]>;
  numberStyle: NumberStyle;
  dateStyle: DateStyle;
  text: string;
}

function quoteIfNeeded(value: string, delimiter: string): string {
  return value.includes(delimiter) || value.includes('"') || value.includes('\n') ? `"${value.replace(/"/g, '""')}"` : value;
}

function styled(field: string, kind: Kind, value: string, spec: RenderSpec, rowIndex: number): string {
  if (value === '') return '';
  if (field === 'unit_cost' || field === 'shipping_cost' || field === 'avg_daily_usage') return formatCents(Number(value.replace('.', '')), spec.numberStyle);
  if (field === 'ship_date' || field === 'estimated_delivery' || field === 'actual_delivery') {
    const [y, m, d] = value.split('-').map(Number) as [number, number, number];
    return formatDate(y, m, d, spec.dateStyle);
  }
  if (field === 'status') {
    const words = Array.isArray(spec.statusWords) ? spec.statusWords : (STATUS_WORDS[spec.statusWords] as readonly string[]);
    return words[STATUSES.indexOf(value)] as string;
  }
  if (field === 'warehouse' && kind === 'inventory') {
    if (spec.warehouseStyle === 'plant') return ['1000', '1010', '2000', '3000', '3010'][WH.indexOf(value)] as string;
    return value;
  }
  void rowIndex;
  return value;
}

export function canonicalCsv(kind: Kind, rows: LogicalRow[]): string {
  const cols = CANONICAL_FIELDS[kind];
  return [cols.join(','), ...rows.map((r) => cols.map((c) => quoteIfNeeded(r[c] ?? '', ',')).join(','))].join('\n') + '\n';
}

function encode(text: string, encoding: Encoding): Uint8Array {
  switch (encoding) {
    case 'utf8':
      return utf8(text);
    case 'utf8bom':
      return utf8Bom(text);
    case 'utf16le':
      return utf16le(text);
    case 'cp1252':
      return cp1252(text);
  }
}

export function makeFixture(name: string, kind: Kind, logical: LogicalRow[], spec: RenderSpec): Fixture {
  const order = spec.order ?? CANONICAL_FIELDS[kind];
  const eol = spec.eol ?? '\n';
  const headers = [...order.map((f) => spec.headers[f] as string), ...(spec.extra ?? []).map((e) => e.header)];
  const truth: Array<string | null> = [...order, ...(spec.extra ?? []).map(() => null)];
  const lines: string[] = [];
  for (const b of spec.banner ?? []) lines.push(b);
  lines.push(headers.map((h) => quoteIfNeeded(h, spec.delimiter)).join(spec.delimiter));
  logical.forEach((row, i) => {
    const cells = [...order.map((f) => styled(f, kind, row[f] ?? '', spec, i)), ...(spec.extra ?? []).map((e) => e.values(i))];
    lines.push(cells.map((c) => quoteIfNeeded(c, spec.delimiter)).join(spec.delimiter));
  });
  if (spec.totalRow !== undefined) lines.push(spec.totalRow.join(spec.delimiter));
  const text = lines.join(eol) + eol;
  const extension = spec.delimiter === '\t' ? '.tsv' : '.csv';
  const words = Array.isArray(spec.statusWords) ? spec.statusWords : (STATUS_WORDS[spec.statusWords] as readonly string[]);
  const statusMap: Array<[string, string]> = words.map((w, i) => [w, STATUSES[i] as string]);
  const plantMap: Array<[string, string]> | undefined =
    spec.warehouseStyle === 'plant' ? [['1000', 'WH-DFW'], ['1010', 'WH-ATL'], ['2000', 'WH-ORD'], ['3000', 'WH-LAX'], ['3010', 'WH-EWR']] : undefined;
  const fixture: Fixture = {
    name,
    kind,
    bytes: encode(text, spec.encoding),
    hints: { fileName: name, extension },
    options: spec.encoding === 'cp1252' ? { encoding: 'windows-1252' } : {},
    truth,
    headers,
    logical,
    // fields the file does not carry are emitted as empty columns by the canonical builder (policy 5.3)
    golden: canonicalCsv(kind, logical.map((row) => Object.fromEntries(CANONICAL_FIELDS[kind].map((c) => [c, order.includes(c) ? (row[c] ?? '') : ''])))),
    statusMap,
    numberStyle: spec.numberStyle,
    dateStyle: spec.dateStyle,
    text
  };
  if (plantMap !== undefined) fixture.warehouseMap = plantMap;
  return fixture;
}

const EN_HEADERS_SHIP = { shipment_id: 'Consignment Reference', origin: 'Pickup From', destination: 'Deliver To', carrier: 'Haulier', status: 'State', ship_date: 'Dispatched On', estimated_delivery: 'ETA', actual_delivery: 'Delivered On', shipping_cost: 'Freight Charge' };

// ---- the named fixtures --------------------------------------------------------------------------------------------------------

export const FIXTURES: Fixture[] = [
  makeFixture('alder_freight.csv', 'shipments', shipmentRows(), {
    headers: EN_HEADERS_SHIP,
    delimiter: ',',
    numberStyle: 'plain',
    dateStyle: 'iso',
    statusWords: ['Delivered', 'Dispatched', 'Booked', 'Cancelled'],
    encoding: 'utf8',
    extra: [{ header: 'Customer Reference', values: (i) => `CR-${4000 + i}` }]
  }),
  makeFixture('casa_verde_es.csv', 'shipments', shipmentRows(), {
    headers: { shipment_id: 'Número de envío', origin: 'Origen', destination: 'Destino', carrier: 'Transportista', status: 'Estado', ship_date: 'Fecha de envío', estimated_delivery: 'Fecha estimada de entrega', actual_delivery: 'Fecha de entrega', shipping_cost: 'Costo de envío' },
    delimiter: ';',
    numberStyle: 'eu',
    dateStyle: 'dmy',
    statusWords: 'es',
    encoding: 'cp1252',
    extra: [{ header: 'Observaciones', values: (i) => `Nota ${i + 1}` }]
  }),
  makeFixture('dreilaender_de.tsv', 'shipments', shipmentRows(), {
    headers: { shipment_id: 'Sendungsnummer', origin: 'Versandort', destination: 'Lieferort', carrier: 'Spediteur', status: 'Sendungsstatus', ship_date: 'Versanddatum', estimated_delivery: 'Liefertermin', actual_delivery: 'Zustelldatum', shipping_cost: 'Frachtkosten' },
    delimiter: '\t',
    numberStyle: 'eu',
    dateStyle: 'dot',
    statusWords: 'de',
    encoding: 'utf16le',
    extra: [{ header: 'Gewicht kg', values: (i) => `${10 + i}.5`.replace('.', ',') }]
  }),
  makeFixture('dai_phat_vi_inventory.csv', 'inventory', inventoryRows(), {
    headers: { sku: 'Mã hàng', product_name: 'Tên sản phẩm', category: 'Nhóm hàng', warehouse: 'Kho', quantity: 'Tồn kho', reorder_point: 'Mức đặt hàng lại', unit_cost: 'Đơn giá', avg_daily_usage: 'Mức tiêu thụ trung bình ngày', lead_time_days: 'Thời gian giao hàng (ngày)' },
    delimiter: ',',
    numberStyle: 'eu',
    dateStyle: 'dmy',
    statusWords: 'vi',
    encoding: 'utf8',
    extra: [{ header: 'Nhà cung cấp', values: (i) => `NCC ${i + 1}` }]
  }),
  makeFixture('dai_phat_vi_shipments.csv', 'shipments', shipmentRows(), {
    headers: { shipment_id: 'Mã vận đơn', origin: 'Nơi gửi', destination: 'Nơi nhận', carrier: 'Đơn vị vận chuyển', status: 'Trạng thái', ship_date: 'Ngày gửi hàng', estimated_delivery: 'Ngày giao dự kiến', actual_delivery: 'Ngày giao thực tế', shipping_cost: 'Cước phí' },
    delimiter: ',',
    numberStyle: 'eu',
    dateStyle: 'dmy',
    statusWords: 'vi',
    encoding: 'utf8',
    extra: [{ header: 'Số kiện', values: (i) => String(1 + i) }]
  }),
  makeFixture('eclair_fr.csv', 'shipments', shipmentRows(), {
    headers: { shipment_id: "Numéro d'expédition", origin: 'Ville de départ', destination: "Ville d'arrivée", carrier: 'Transporteur', status: 'Statut', ship_date: "Date d'expédition", estimated_delivery: 'Date de livraison prévue', actual_delivery: 'Date de livraison réelle', shipping_cost: 'Coût du transport' },
    delimiter: ';',
    numberStyle: 'fr',
    dateStyle: 'dmy',
    statusWords: 'fr',
    encoding: 'utf8',
    extra: [{ header: 'Poids', values: (i) => `${10 + i},5` }]
  }),
  makeFixture('fjord_sap_inventory.csv', 'inventory', inventoryRows(), {
    headers: { sku: 'Material Number', product_name: 'Material Description', category: 'Material Group', warehouse: 'Plant', quantity: 'Unrestricted Qty', reorder_point: 'Reorder Point', unit_cost: 'Std Price' },
    order: ['sku', 'product_name', 'category', 'warehouse', 'quantity', 'reorder_point', 'unit_cost'],
    delimiter: '|',
    numberStyle: 'plain',
    dateStyle: 'iso',
    statusWords: 'en',
    encoding: 'utf8',
    warehouseStyle: 'plant',
    extra: [{ header: 'Base Unit of Measure', values: (i) => ['EA', 'PC', 'BX'][i % 3] as string }]
  }),
  makeFixture('kestrel_paste.tsv', 'inventory', inventoryRows(), {
    headers: { sku: 'Item Code', product_name: 'Item Description', category: 'Product Category', warehouse: 'WH', quantity: 'Qty', reorder_point: 'Reorder Level', unit_cost: 'Unit Price', avg_daily_usage: 'Daily Usage', lead_time_days: 'Lead Time' },
    delimiter: '\t',
    numberStyle: 'plain',
    dateStyle: 'iso',
    statusWords: 'en',
    encoding: 'utf8',
    eol: '\r\n'
  }),
  makeFixture('brightwater_banner.csv', 'inventory', inventoryRows(), {
    headers: { sku: 'Item No.', product_name: 'Description', category: 'Dept', warehouse: 'Warehouse Code', quantity: 'Quantity on Hand', reorder_point: 'Min Level', unit_cost: 'Unit Cost USD', avg_daily_usage: 'Avg Daily Demand', lead_time_days: 'Lead Time (Days)' },
    delimiter: ',',
    numberStyle: 'plain',
    dateStyle: 'iso',
    statusWords: 'en',
    encoding: 'utf8bom',
    banner: ['Brightwater Stores - Inventory valuation', 'Printed 2026-03-31, all warehouses', ''],
    totalRow: ['Total', '', '', '', '5200', '', '', '', '']
  })
];

export function fixtureByName(name: string): Fixture {
  const f = [...FIXTURES, ...AMBIGUITY_FIXTURES].find((x) => x.name === name);
  if (f === undefined) throw new Error(`unknown fixture ${name}`);
  return f;
}

// ---- ambiguity and structure fixtures (no golden canonical output unless stated) -------------------------------------------------

const textFixture = (name: string, kind: Kind, text: string, truth: Array<string | null>, encoding: Encoding = 'utf8'): Fixture => ({
  name,
  kind,
  bytes: encode(text, encoding),
  hints: { fileName: name, extension: name.endsWith('.tsv') ? '.tsv' : '.csv' },
  options: {},
  truth,
  headers: (text.split('\n')[0] as string).split(','),
  logical: [],
  golden: '',
  statusMap: [],
  numberStyle: 'plain',
  dateStyle: 'iso',
  text
});

const shipHead = 'shipment_id,origin,destination,carrier,status,ship_date,estimated_delivery,actual_delivery,shipping_cost';
const shipTruth = SHIPMENT_FIELDS;
const invHead = 'sku,product_name,category,warehouse,quantity,reorder_point,unit_cost';

export const AMBIGUITY_FIXTURES: Fixture[] = [
  textFixture('slash_dates_ambiguous.csv', 'shipments', [shipHead, 'SHP-900001,WH-DFW,Houston TX,Northstar,delivered,03/04/2026,05/04/2026,06/04/2026,812.40', 'SHP-900002,WH-ATL,Miami FL,BlueLine,delivered,05/06/2026,07/06/2026,08/06/2026,640.00'].join('\n') + '\n', shipTruth),
  textFixture('numbers_1_250_ambiguous.csv', 'inventory', [invHead, 'ELC-9001,Scanner,Electronics,WH-DFW,120,40,"1,250"', 'ELC-9002,Printer,Electronics,WH-ATL,60,20,"1,250"'].join('\n') + '\n', invHead.split(',')),
  textFixture('dates_mixed.csv', 'shipments', [shipHead, 'SHP-900001,WH-DFW,Houston TX,Northstar,delivered,2026-03-02,2026-03-05,2026-03-06,812.40', 'SHP-900002,WH-ATL,Miami FL,BlueLine,delivered,8/15/2026,8/17/2026,8/18/2026,640.00'].join('\n') + '\n', shipTruth),
  textFixture('numbers_mixed.csv', 'inventory', [invHead, 'ELC-9001,Scanner,Electronics,WH-DFW,120,40,"89,50"', 'ELC-9002,Printer,Electronics,WH-ATL,60,20,12.5'].join('\n') + '\n', invHead.split(',')),
  textFixture('mystery_columns.csv', 'shipments', ['Col1,Col2,Col3,Col4,Col5', 'A100,Houston,delivered,4,x1', 'A101,Miami,in_transit,7,x2', 'A102,Denver,pending,2,x3', 'A103,Boston,cancelled,9,x4', 'A104,Seattle,delivered,1,x5'].join('\n') + '\n', [null, null, 'status', null, null]),
  textFixture(
    'both_kinds_16_columns.csv',
    'inventory',
    ['sku,product_name,category,warehouse,quantity,reorder_point,unit_cost,shipment_id,origin,destination,carrier,status,ship_date,estimated_delivery,actual_delivery,shipping_cost', 'ELC-9001,Scanner,Electronics,WH-DFW,120,40,89.50,SHP-900001,WH-DFW,Houston TX,Northstar,delivered,2026-03-02,2026-03-05,2026-03-06,812.40', 'ELC-9002,Printer,Electronics,WH-ATL,60,20,210.00,SHP-900002,WH-ATL,Miami FL,BlueLine,pending,2026-03-03,2026-03-06,,640.00'].join('\n') + '\n',
    [...invHead.split(','), ...SHIPMENT_FIELDS]
  )
];

export { concat };
