// Criterion 11: header-row detection (banner/title rows, blank lines, repeated header rows), structural rows listed and
// excluded only after the user's confirmation, the "Header is on row N" override, and format independence (works on
// generic tables, including ones whose source names its own columns).

import { describe, expect, it } from 'vitest';
import type { RawCell, RawTable } from '../../../src/shared/ingest/types';
import { applyStructure, columnCells, detectStructure, findStructuralRows } from '../../../src/shared/ingest/structure/detectStructure';
import { recognizesHeader } from '../../../src/shared/ingest/mapping/dictionary';

function tableOf(rows: string[][], over: Partial<RawTable> = {}): RawTable {
  const cells: RawCell[][] = rows.map((r) => r.map((v): RawCell => ({ v, t: 'text' })));
  let colCount = 0;
  for (const r of cells) colCount = Math.max(colCount, r.length);
  return {
    ref: { adapterId: 'test', name: 'Data', index: 0 },
    name: 'Data',
    hidden: false,
    rows: cells,
    rowCount: cells.length,
    colCount,
    truncated: false,
    origin: (r: number, c?: number) => (c === undefined ? { kind: 'line', line: r + 1 } : { kind: 'line', line: r + 1, column: c + 1 }),
    notes: [],
    ...over
  };
}

const HEAD = ['sku', 'product_name', 'category', 'warehouse', 'quantity', 'reorder_point', 'unit_cost'];
const R1 = ['ELC-9001', 'Scanner', 'Electronics', 'WH-DFW', '120', '40', '89.50'];
const R2 = ['PKG-1001', 'Pallet Wrap', 'Packaging', 'WH-ATL', '900', '300', '24.99'];
const R3 = ['SAF-2001', 'Gloves', 'Safety', 'WH-ORD', '450', '100', '4.25'];
const detect = (t: RawTable) => detectStructure(t, recognizesHeader);

describe('header row detection', () => {
  it('a plain table has its header on the first row with no banner and no structural rows', () => {
    const d = detect(tableOf([HEAD, R1, R2, R3]));
    expect(d).toMatchObject({ headerRowIndex: 0, confidence: 'detected', bannerRows: [], structuralRows: [] });
    expect(d.evidence.join(' ')).toContain('7 recognized column name(s) in row 1');
  });

  it('skips banner and title rows above the header', () => {
    const d = detect(tableOf([['Stock report'], ['Printed 2026-03-31 for Alder Stores', ''], ['Filter: all warehouses'], HEAD, R1, R2, R3]));
    expect(d.headerRowIndex).toBe(3);
    expect(d.bannerRows).toEqual([0, 1, 2]);
    expect(d.confidence).toBe('detected');
    expect(d.evidence.join(' ')).toContain('3 row(s) above the header');
  });

  it('finds an unrecognized header (generic names) below a banner by its shape', () => {
    const d = detect(tableOf([['Quarterly export'], ['Col A', 'Col B', 'Col C', 'Col D'], ['12', '3.5', 'x', '2026-03-01'], ['14', '4.5', 'y', '2026-03-02'], ['15', '5.5', 'z', '2026-03-03']]));
    expect(d.headerRowIndex).toBe(1);
    expect(d.bannerRows).toEqual([0]);
  });

  it('works in any language (the dictionary recognizes the names)', () => {
    const vi = tableOf([['Báo cáo tồn kho'], ['Mã hàng', 'Tên sản phẩm', 'Nhóm hàng', 'Kho', 'Tồn kho'], ['A1', 'Bulong', 'Kim khí', 'WH-DFW', '5'], ['A2', 'Đai ốc', 'Kim khí', 'WH-ATL', '9']]);
    expect(detect(vi).headerRowIndex).toBe(1);
  });

  it('reports low confidence when two rows look equally like a header, so the UI can ask "Header is on row N"', () => {
    const d = detect(tableOf([['Red', 'Green', 'Blue', 'Amber'], ['Cyan', 'Teal', 'Plum', 'Rose'], ['x1', 'y2', 'z3', 'w4']]));
    expect(d.confidence).not.toBe('detected');
    expect(d.candidates.length).toBeGreaterThanOrEqual(2);
    expect(d.candidates.map((c) => c.rowIndex)).toContain(0);
    expect(d.candidates.map((c) => c.rowIndex)).toContain(1);
  });

  it('a source that names its own columns has no header row to find', () => {
    const t = tableOf([R1, R2], { columns: HEAD.map((header) => ({ header })) });
    const d = detect(t);
    expect(d.confidence).toBe('detected');
    const st = applyStructure(t, d.headerRowIndex);
    expect(st.headers).toEqual(HEAD);
    expect(st.rows).toHaveLength(2);
    expect(st.sourceRowIndex).toEqual([0, 1]);
  });

  it('handles degenerate tables without throwing', () => {
    expect(detect(tableOf([])).confidence).toBe('choose');
    expect(detect(tableOf([HEAD])).headerRowIndex).toBe(0);
    expect(detect(tableOf([['only one cell']])).headerRowIndex).toBe(0);
    expect(detect(tableOf([[''], ['']])).headerRowIndex).toBeGreaterThanOrEqual(0);
  });
});

describe('structural rows are listed, and excluded only after confirmation', () => {
  const body = [HEAD, R1, R2, HEAD, R3, ['Total', '', '', '', '1470', '', ''], ['Generated by the ERP on 2026-03-31'], ['Page 1 of 1']];
  const t = tableOf(body);

  it('lists repeated header rows, total rows and footers with their row numbers', () => {
    const d = detect(t);
    expect(d.headerRowIndex).toBe(0);
    expect(d.structuralRows.map((r) => [r.rowIndex, r.kind, r.label])).toEqual([
      [3, 'repeated-header', 'sku'],
      [5, 'total', 'Total'],
      [6, 'footer', 'Generated by the ERP on 2026-03-31'],
      [7, 'footer', 'Page 1 of 1']
    ]);
    expect(t.origin(3)).toEqual({ kind: 'line', line: 4 }); // shown to the user as a line number
  });

  it('keeps every row until the user confirms, then removes exactly the confirmed ones', () => {
    const d = detect(t);
    const none = applyStructure(t, 0, [], d);
    expect(none.rows).toHaveLength(7);
    expect(none.excluded).toEqual([]);
    const some = applyStructure(t, 0, [5], d);
    expect(some.rows).toHaveLength(6);
    expect(some.excluded).toEqual([{ rowIndex: 5, kind: 'total' }]);
    const all = applyStructure(t, 0, d.structuralRows.map((r) => r.rowIndex), d);
    expect(all.rows.map((r) => r[0]?.v)).toEqual(['ELC-9001', 'PKG-1001', 'SAF-2001']);
    expect(all.sourceRowIndex).toEqual([1, 2, 4]);
    expect(all.excluded.map((e) => e.kind)).toEqual(['repeated-header', 'total', 'footer', 'footer']);
  });

  it('total words of the five languages are recognized, and a row needs numbers to count as a total', () => {
    for (const word of ['Total', 'SUBTOTAL', 'Grand Total', 'Gesamt', 'Summe', 'Tổng cộng', 'Total general', 'Somme', 'Suma']) {
      const rows = findStructuralRows(tableOf([HEAD, R1, [word, '', '', '', '500', '', ''], R2]), 0);
      expect(rows.map((r) => r.kind), word).toEqual(['total']);
    }
    // "Total Wine Shop" is a product name, not a total: no numbers elsewhere in the row
    expect(findStructuralRows(tableOf([HEAD, R1, ['Total Wine Shop', 'x', 'y', 'z', '', '', ''], R2]), 0)).toEqual([]);
  });

  it('a data row with a single filled cell is not a footer unless it is at the end', () => {
    const rows = findStructuralRows(tableOf([HEAD, R1, ['lonely', '', '', '', '', '', ''], R2, R3]), 0);
    expect(rows).toEqual([]);
  });

  it('the header override ("Header is on row N") re-reads the table from that row', () => {
    const banner = tableOf([['Report'], HEAD, R1, R2]);
    const st = applyStructure(banner, 1);
    expect(st.headers).toEqual(HEAD);
    expect(st.headerRowIndex).toBe(1);
    expect(st.rows).toHaveLength(2);
    const wrong = applyStructure(banner, 0);
    expect(wrong.headers).toEqual(['Report']);
    expect(wrong.rows).toHaveLength(3);
  });

  it('columnCells reads a missing cell as blank', () => {
    const st = applyStructure(tableOf([['a', 'b'], ['1'], ['2', '3']]), 0);
    expect(columnCells(st, 1).map((c) => c.v)).toEqual(['', '3']);
  });
});
