// @vitest-environment jsdom
// Criteria 11, 18, 24 (UI side), 40 and 51: the structure panel (header row override, banner rows, total rows needing the
// user's confirmation), the table picker (fieldset/legend radio group, nothing preselected, hidden tables collapsed) and
// the dataset choice, with the real pipeline and the fake multi-table adapter.

import { describe, expect, it, beforeEach, vi } from 'vitest';
import { screen, waitFor, within, render } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createDefaultRegistry } from '../../../src/shared/ingest/adapters';
import { StructurePanel } from '../../../src/client/components/import/StructurePanel';
import { TablePicker } from '../../../src/client/components/import/TablePicker';
import { encodeMulti, multiTableAdapter, type FakeSheet } from '../../ingest-kit/fakeAdapters';
import { renderCard, review, settled, acknowledgeAll, fileOf, fileOfFixture, fixtureByName, confirmButton } from './uiHarness';

beforeEach(() => {
  window.location.hash = '';
});

const HEAD = ['shipment_id', 'origin', 'destination', 'carrier', 'status', 'ship_date', 'estimated_delivery', 'actual_delivery', 'shipping_cost'];
const text = (v: string) => ({ v, t: 'text' as const });
const sheetOf = (name: string, hidden = false): FakeSheet => ({
  name,
  hidden,
  rows: [
    HEAD.map(text),
    ['SHP-901', 'WH-DFW', 'Houston TX', 'Alder', 'delivered', '2026-03-02', '2026-03-05', '2026-03-05', '10.00'].map((v, i) => ({ v, t: i === 5 || i === 6 || i === 7 ? ('date' as const) : i === 8 ? ('number' as const) : ('text' as const) })),
    ['SHP-902', 'WH-ATL', 'Miami FL', 'Alder', 'pending', '2026-03-03', '2026-03-06', '', '11.00'].map((v, i) => ({ v, t: i === 5 || i === 6 ? ('date' as const) : i === 8 ? ('number' as const) : ('text' as const) }))
  ]
});

function registryWithFakes() {
  const registry = createDefaultRegistry();
  registry.register(multiTableAdapter);
  return registry;
}

// Each decision re-runs the whole pipeline on a real file; under a loaded parallel run that can pass 5 s (as in
// blockingStates and ImportPage.mapping), so this group gets the same 15 s budget. The assertions are unchanged.
describe('structure panel with a real file', { timeout: 15_000 }, () => {
  it('shows banner rows, the header row and the total row; the total row is only left out after the user ticks it', async () => {
    const r = await renderCard();
    await review(r, fileOfFixture(fixtureByName('brightwater_banner.csv')));
    const panel = screen.getByRole('heading', { name: 'Structure of the table' }).closest('section') as HTMLElement;
    expect(within(panel).getByText(/Column names are on line \d+\./)).toBeInTheDocument();
    expect(within(panel).getByText(/rows? above the column names (is|are) not imported/)).toBeInTheDocument();
    const checkbox = within(panel).getByRole('checkbox', { name: /Leave out total or subtotal at line \d+/ }) as HTMLInputElement;
    expect(checkbox.checked).toBe(false);
    await acknowledgeAll(r.user);
    // while the total row stays in, the validation reports it with the user's own row reference
    await waitFor(() => expect(screen.queryAllByText(/problems? found in the data/).length).toBeGreaterThan(0));
    expect(confirmButton()).toBeDisabled();
    await r.user.click(checkbox);
    await settled();
    expect(screen.getByText(/Left out: 1 total rows\./)).toBeInTheDocument();
    await acknowledgeAll(r.user);
    await waitFor(() => expect(confirmButton()).toBeEnabled());
  });

  it('"Header is on row N" overrides the detected row and re-reads the table', async () => {
    const r = await renderCard();
    await review(r, fileOfFixture(fixtureByName('brightwater_banner.csv')));
    const input = screen.getByLabelText('Header is on row') as HTMLInputElement;
    const detected = input.value;
    expect(Number(detected)).toBeGreaterThan(1);
    await r.user.clear(input);
    await r.user.type(input, '1');
    await r.user.click(screen.getByRole('button', { name: 'Use this row' }));
    await settled();
    // the banner line is now taken as the header: its text is no SCC field, so the columns are no longer matched
    expect(screen.getByText(/Column names are on line 1\./)).toBeInTheDocument();
    expect(confirmButton()).toBeDisabled();
  });
});

describe('structure panel (component)', () => {
  const structure = { headerRow: 'line 4', confidence: 'choose' as const, evidence: ['Row 4 has the most recognised names.'], banners: 3, structuralRows: [{ rowIndex: 9, kind: 'footer' as const, label: 'Generated by <b>ERP</b>', where: 'line 12', excluded: false }] };

  it('asks to confirm an uncertain header row and renders hostile text as text', async () => {
    const onHeaderRow = vi.fn();
    const onExclude = vi.fn();
    const user = userEvent.setup();
    const { container } = render(<StructurePanel structure={structure} needsConfirmation busy={false} onHeaderRow={onHeaderRow} onExclude={onExclude} />);
    expect(screen.getByText('Generated by <b>ERP</b>')).toBeInTheDocument();
    expect(container.querySelector('b')).toBeNull();
    await user.click(screen.getByRole('button', { name: 'Confirm header row 4' }));
    expect(onHeaderRow).toHaveBeenCalledWith(3);
    await user.click(screen.getByRole('checkbox', { name: /Leave out footer at line 12/ }));
    expect(onExclude).toHaveBeenCalledWith(9, true);
    expect(screen.getByRole('heading', { name: 'Structure of the table' })).toHaveAttribute('tabindex', '-1');
  });

  it('refuses a header row number below 1', async () => {
    const onHeaderRow = vi.fn();
    const user = userEvent.setup();
    render(<StructurePanel structure={{ ...structure, confidence: 'detected' }} needsConfirmation={false} busy={false} onHeaderRow={onHeaderRow} onExclude={vi.fn()} />);
    const input = screen.getByLabelText('Header is on row');
    await user.clear(input);
    await user.type(input, '0');
    expect(screen.getByRole('button', { name: 'Use this row' })).toBeDisabled();
  });
});

describe('table picker', () => {
  const book = () => encodeMulti([sheetOf('Loads'), sheetOf('Loads 2'), sheetOf('Archive', true)]);

  it('two visible sheets: a fieldset/legend radio group with nothing preselected, hidden sheets collapsed, Confirm blocked until one is chosen', async () => {
    const r = await renderCard({ registry: registryWithFakes() });
    await review(r, fileOf(book(), 'two.mtc'));
    const group = screen.getByRole('group', { name: /Choose the table to import/ });
    const radios = within(group).getAllByRole('radio') as HTMLInputElement[];
    expect(radios).toHaveLength(3); // two visible, one inside the collapsed "Hidden tables"
    expect(radios.every((x) => !x.checked)).toBe(true);
    expect(within(group).getByText('Hidden tables (1)').closest('details')).not.toHaveAttribute('open');
    expect(screen.getAllByText(/This file has 2 tables\. Choose the one to import\./).length).toBeGreaterThan(0);
    expect(confirmButton()).toBeDisabled();
    await r.user.click(within(group).getByRole('radio', { name: /Loads 2/ }));
    await settled();
    expect((within(screen.getByRole('group', { name: /Choose the table to import/ })).getByRole('radio', { name: /Loads 2/ }) as HTMLInputElement).checked).toBe(true);
    await acknowledgeAll(r.user);
    await waitFor(() => expect(confirmButton()).toBeEnabled());
    expect(screen.getByText(/rows from two.mtc > Loads 2./)).toBeInTheDocument();
    // source references name the sheet and the row of the user's workbook
    expect(screen.getAllByText(/Sheet 'Loads 2', row 2/).length).toBeGreaterThan(0);
  });

  it('a workbook with one visible sheet needs no table picker', async () => {
    const r = await renderCard({ registry: registryWithFakes() });
    await review(r, fileOf(encodeMulti([sheetOf('Loads'), sheetOf('Notes', true)]), 'one.mtc'));
    expect(screen.queryByRole('group', { name: /Choose the table to import/ })).not.toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Review before importing' })).toBeInTheDocument();
  });

  it('component: the keyboard can reach and operate every radio, and hostile sheet names are text', async () => {
    const onSelect = vi.fn();
    const user = userEvent.setup();
    const preview = {
      tables: [
        { name: '<img src=x onerror=alert(1)>', hidden: false, rows: 5, selected: false },
        { name: 'Second', hidden: false, rows: null, selected: false }
      ],
      blockers: [{ code: 'choose-table', message: 'x', fatal: false }]
    } as unknown as Parameters<typeof TablePicker>[0]['preview'];
    const { container } = render(<TablePicker preview={preview} busy={false} onSelect={onSelect} />);
    expect(container.querySelector('img')).toBeNull();
    expect(screen.getByText(/<img src=x onerror=alert\(1\)>/)).toBeInTheDocument();
    await user.tab(); // heading is not a tab stop; the first radio is
    expect(document.activeElement).toBe(screen.getAllByRole('radio')[0]);
    await user.keyboard(' ');
    expect(onSelect).toHaveBeenCalledWith(0);
    await user.keyboard('{ArrowDown}');
    expect(onSelect).toHaveBeenCalledWith(1);
  });
});
